### ISSUE TITLE
Alteração no sistema de header/footer

### ISSUE THREAD

**Issue by marcalderdelma** [GabrielCoelho/TechTrain#1]
Pessoal, o binho alterou algumas coisas no sistema de header e footer que atrapalhavam o redirecionamento das páginas.

**Comment by marcalderdelma** [comment]
Observem que obrigatoriamente precisaremos incluir os arquivos de header e footer nas demais páginas, evitando a gambiarra anterior. Para resolver os problemas de templating, o binho mostrou um template engine chamado twig. Ele disse que se quisermos, elem mostra como utilizar! 😄

**Comment by marcalderdelma** [comment]
@GabrielCoelho @viniciuscbecaleti @lfrclnando @richardgdias @Eradamus

**Comment by GabrielCoelho** [comment]
Agradeço! O vinicius não foi hoje?

**Comment by lfrclnando** [comment]
Ok Marc!!!
Obrigado!!!
