### ISSUE TITLE
Alteração

### ISSUE THREAD

**Issue by marcalderdelma** [GabrielCoelho/TechTrain#2]
Olá, pessoal, até agora nós temos as rotas:  /register, /post-register, /login, /logout, /editProfile, /editName, /changeEmail, /changePassword, cujas as funções respectivamente são: redirecionar para a página de cadastro, efetuar o cadastro incluindo os dados do usuário no banco de dados, permitir ao usuário fazer login no sistema, permitir ao usuário fazer logout no sistema, redirecionar para a página de edição do perfil, editar o nome, alterar o e-mail, alterar a senha.

**Comment by GabrielCoelho** [comment]
Grato pela informação Marc! 
![bitmoji](https://render.bitstrips.com/v2/cpanel/8968004-312071007_10-s4-v1.png?transparent=1&palette=1&width=246)
