### ISSUE TITLE
Rota Cursos

### ISSUE THREAD

**Issue by GabrielCoelho** [GabrielCoelho/TechTrain#3]
## Mudanças feitas na rota
No commit e63a0fa5d0b5c69103d0670ceaba7dbf5d3e1bcc eu alterei a tabela `curso` no banco de dados, retirando a Foreign Key do idCertificado. O motivo de retirar foi para conseguir adicionar curso sem ter que adicionar um certificado previamente. 
Além disso, melhorei o design da página de Cursos. **Ainda assim, está faltando o código PHP para que sejam listados os cursos corretamente.**
* * *
### Lista de Afazeres
- [X] Design
- [X] Conseguir listar os cursos cadastrados
- [x] Conseguir mostrar os cursos corretamente
- [ ] Manter o Design proposto 

* * *
Aguardo Respostas!
![bitmoji](https://render.bitstrips.com/v2/cpanel/10139133-312071007_10-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by GabrielCoelho** [comment]
#### Nota pós publicação: 
O **Ponto 2** da _lista de afazeres_ já está sendo chamado pelo [CourseController.php][link1]. Para que você consiga ver, tire os comentários das linhas 13 e 14.
~~~php
// eles estão assim:
// print_r($array);
// die();

// Tire as barras para visualizar:
print_r($array);
die();

/*
Vá para a rota /courses
*/
~~~

[link1]: https://github.com/GabrielCoelho/TechTrain/blob/master/app/Controller/CourseController.php

**Comment by GabrielCoelho** [comment]
## Adição da página de cada curso! 
no commit 46e7d30ef96200510634a42c5eb9a312cb8c6d94 eu dei finalização a **ideia** de página para curso. Ainda existem coisas que podem ser adicionadas, como comentários de curso, avaliação do mesmo e _n_ outras. 

## Comentários sobre a Ideia de ter apenas uma página
A ideia que tive é a seguinte: 
> **Na página de cursos, cada um dos links indicam para uma rota em específico. Nem que seja para fazermos com formulários para que envie algo indicando que seja o curso X e não o curso Y que a pessoa quer ver.**
> **Assim, pelo `CourseController->clickCourse()` nós podemos fazer a pesquisa/seleção dos dados no DB onde (exemplo) o idCurso no banco seja igual ao passado através do click. E passar as informações através de um array.**

Seria algo como:
~~~php
//inicia o objeto do QueryBuilder
$q = new QueryBuilder();
//Faz o select armazenando os dados em um array
$curso = $q->select('curso', $_POST['dadoCurso'] = 'idCurso'); //Note que não está pronto, isso é apenas um exemplo!
~~~
* * *
### Como está a página de Curso: 
![screen shot 2017-10-27 at 18 25 53](https://user-images.githubusercontent.com/22378797/32123837-7f5a539e-bb44-11e7-91a3-7915c0932d31.png)

### Como está a página de **cada** Curso:
![screenshot-2017-10-27 techtrain](https://user-images.githubusercontent.com/22378797/32123960-f4b67f32-bb44-11e7-97a7-6b8022aa9072.png)

* * *

**Comment by lfrclnando** [comment]
Eu gostei. Ficou muito bom!!!

**Comment by GabrielCoelho** [comment]
Eu ajustei a página para deixar o site na versão mobile mais responsivo. 
As alterações foram nas `divs` que separam os cursos. 
a classe estava assim: 

~~~html
<div class="col-md-3 col-xs-3">
 <!-- Conteúdo -->
</div>
~~~


e alterei para esta forma:

~~~html
<div class="col-sm-3 col-xs-12">
 <!-- Conteúdo -->
</div>
~~~

**Comment by lfrclnando** [comment]
Sobre a Query da imagem para o Banco de Dados ainda estou trabalhando!!!

**Comment by lfrclnando** [comment]
Galera...
Criei outro BD para teste com uma modificação na tabela Curso e Certificado. Vejam a modificação neste commit 2b28f12.
A ideia é testar outra configuração.
Sobre a Tabela Curso e Certificado, estou fazendo alguns testes ainda e explicarei mais adiante!!!

Valeu

**Comment by lfrclnando** [comment]
Aliás...
Em meu PC, não está funcionando o PHPMYADMIN. Infelizmente não estou conseguindo instalar o MYSQL do APACHE em outra porta. Eu uso o MYSQL WORKBENCH.
Não estranhem porque o DUMP não está na versão PHPMYADMIN.

E também neste banco não está com a tabela aula.

Valeu....

**Comment by lfrclnando** [comment]
Batata Beleza?!
Eu coloquei dois arquivos
o banco.sql e o banco_tech_train.sql.

O arquivo banco.sql é Dump, já o arquivo banco_tech_train.sql é o script.

Ok.

**Comment by lfrclnando** [comment]
Subi no GitHub as alterações que foram feitas na aula de sexta feira dia 17/11/17.
Não fiz um teste profundo. O Binho (Professor) ajudou com relação ás pesquisas em trazer os cursos.
Mas ainda está falhando. Sobre a programação eu só fiz o envio porque foi uma mudança grande além também que se houvesse alguma alteração talvez teria que refazer essa parte do código que o Marc, Michell com a ajuda do Binho fizeram.
Sobre o Banco e a documentação do Análise, eu fiz alguns outros ajustes.

**Comment by lfrclnando** [comment]
Galera...
Subi mais uma alteração de acréscimo no BD.
Desta vez coloquei alguns campos em UNIQUE,  acrescentei a tabela professores para inserção de seus dados e também farei as normalizações NF1, NF2 e NF3 das tabelas do Banco juntamente com uma segurança á mais . Se acaso tivermos tempo pra isso. Rsrsrss...

Na documentação UML consertei o problema de INCLUDE E EXTEND, além de um dizeres  nos requisitos.
e logo estarei, subindo o Caso de Uso de Professores e também de Usuários e seus Diagramas se tudo der certo!! 

É isso!!!!

**Comment by GabrielCoelho** [comment]
Fechando a Issue, não há nada a mais para por aqui.
