### ISSUE TITLE
Adição de um campo no Banco de Dados

### ISSUE THREAD

**Issue by GabrielCoelho** [GabrielCoelho/TechTrain#4]
## Tabela Curso
Precisa de um campo para salvarmos o caminho da imagem do curso. 
O campo pode ser em varchar mesmo, com no **máximo** 80 caracteres. Assim, podemos, quando puxar o Select e a partir dele, puxar a imagem correta também! 

~~~php
$q = new QueryBuilder();
$arrayExemplo = $q->select('curso');

echo $arrayExemplo[0]['imagemCurso'];
~~~
O Output desse `echo` seria:
`./public/imagem/curso/php1.jpg`
* * * 
**Assim, poderemos simplesmente dar este echo dentro da tag IMG no código HTML.**
~~~php
<img src="<?= $arrayExemplo[0]['imagemCurso]?>" alt="imagem curso 01">
~~~

* * * 
Abraços
![bitmoji](https://render.bitstrips.com/v2/cpanel/10212428-312071007_10-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by lfrclnando** [comment]
Ok pode deixar!!!!

**Comment by GabrielCoelho** [comment]
Completo pelo commit f215668a1bd4cad6a7c459e01a8a82fa63ad7ccb 
Agradeço @lfrclnando
